export const NAT: Record<string, string> = {
  ITA: "🇮🇹 Italia",
  ARG: "🇦🇷 Argentina",
  BRA: "🇧🇷 Brasile",
  FRA: "🇫🇷 Francia",
  ESP: "🇪🇸 Spagna",
  GER: "🇩🇪 Germania",
  ENG: "🏴 Inghilterra",
  POR: "🇵🇹 Portogallo",
  NED: "🇳🇱 Olanda",
  BEL: "🇧🇪 Belgio",
  CRO: "🇭🇷 Croazia",
  SRB: "🇷🇸 Serbia",
  POL: "🇵🇱 Polonia",
  DEN: "🇩🇰 Danimarca",
  SWE: "🇸🇪 Svezia",
  NOR: "🇳🇴 Norvegia",
  SUI: "🇨🇭 Svizzera",
  AUT: "🇦🇹 Austria",
  TUR: "🇹🇷 Turchia",
  GRE: "🇬🇷 Grecia",
  ALB: "🇦🇱 Albania",
  KVX: "🇽🇰 Kosovo",
  SVN: "🇸🇮 Slovenia",
  SVK: "🇸🇰 Slovacchia",
  CZE: "🇨🇿 Cechia",
  UKR: "🇺🇦 Ucraina",
  SCO: "🏴 Scozia",
  WAL: "🏴 Galles",
  IRL: "🇮🇪 Irlanda",
  ISL: "🇮🇸 Islanda",
  FIN: "🇫🇮 Finlandia",
  USA: "🇺🇸 USA",
  CAN: "🇨🇦 Canada",
  MEX: "🇲🇽 Messico",
  COL: "🇨🇴 Colombia",
  URU: "🇺🇾 Uruguay",
  CHI: "🇨🇱 Cile",
  PAR: "🇵🇾 Paraguay",
  ECU: "🇪🇨 Ecuador",
  PER: "🇵🇪 Perù",
  VEN: "🇻🇪 Venezuela",
  MAR: "🇲🇦 Marocco",
  ALG: "🇩🇿 Algeria",
  TUN: "🇹🇳 Tunisia",
  EGY: "🇪🇬 Egitto",
  SEN: "🇸🇳 Senegal",
  CIV: "🇨🇮 Costa d'Avorio",
  GHA: "🇬🇭 Ghana",
  NGA: "🇳🇬 Nigeria",
  CMR: "🇨🇲 Camerun",
  MLI: "🇲🇱 Mali",
  BFA: "🇧🇫 Burkina Faso",
  GUI: "🇬🇳 Guinea",
  GAM: "🇬🇲 Gambia",
  COD: "🇨🇩 RD Congo",
  ANG: "🇦🇴 Angola",
  JPN: "🇯🇵 Giappone",
  KOR: "🇰🇷 Corea del Sud",
  AUS: "🇦🇺 Australia",
  NZL: "🇳🇿 Nuova Zelanda",
  GEO: "🇬🇪 Georgia",
  ARM: "🇦🇲 Armenia",
  MKD: "🇲🇰 Macedonia N.",
  MNE: "🇲🇪 Montenegro",
  BIH: "🇧🇦 Bosnia",
  HUN: "🇭🇺 Ungheria",
  ROU: "🇷🇴 Romania",
  BUL: "🇧🇬 Bulgaria",
  EST: "🇪🇪 Estonia",
  LVA: "🇱🇻 Lettonia",
  LTU: "🇱🇹 Lituania",
  ISR: "🇮🇱 Israele",
  IRN: "🇮🇷 Iran",
};
